### ISSUE TITLE
bpfman CSI plugin and bpfman CRDs don't align

### ISSUE THREAD

**Issue by dave-tucker** [bpfman/bpfman-operator#386]
Lets say I have a `BpfApplication` called `my-bpf-application`, which has 3 probes: `my-kprobe`, `my-uprobe` and `my-xdp-probe`.
The maps used by these probes are as follows:

- `stats-map` = used by all
- `xdp-map` = used by xdp only

When using the CSI plugin to access these maps, using the `csi.bpfman.io/program` volume attribute is weird because the maps are owned by the application, not the program. So technically speaking, after #347 merges, the following syntax is valid:

```yaml
volumeAttributes:
            csi.bpfman.io/program: my-kprobe
            csi.bpfman.io/maps: xdp-map  # this is weird because its only used by the xdp probe
```

You may also be tempted (as reported by a user on Slack) to do something like this, which is not valid:

```yaml
volumeAttributes:
            csi.bpfman.io/program: my-kprobe, my-xdp-probe, my-uprobe # this isn't valid
            csi.bpfman.io/maps: stats-map, xdp-map 
```

I believe that what we should be doing instead is:
```
volumeAttributes:
            csi.bpfman.io/application: my-bpf-application
            csi.bpfman.io/maps: stats-map, xdp-map 
```

I'll open a bpfman issue (where the fix will need to be) to address this.
